resolve #1293
napalm-automation/napalm pull request #1382
Opened 2021-02-23 18:56 UTC by minefuto

This is related to #1293.
I added support for logical interface counters of Junos.

2021-03-04 12:47 UTC, mirceaulinic requested changes
Good start @minefuto, thanks for having a go at this. I've requested some changes, as I wouldn't want to increase the complexity while the data is already available.

2021-03-04 12:47 UTC, mirceaulinic commented on napalm/junos/junos.py
> +        query_logical = junos_views.junos_logical_iface_counter_table(self.device)
I don't think we should make a separate request just for this: the logical interfaces are already present in the `junos_iface_counter_table`, we just need to extract them. For this we can use the nested tables junos-eznc offers, see an example [here](https://github.com/napalm-automation/napalm/blob/develop/napalm/junos/utils/junos_views.yml#L64-L75) where a view is able to reference a  sub-table. In the same way, we can have the logical interfaces nested under a sub-table, and avoid an additional RPC request.

2021-03-05 11:29 UTC, minefuto commented
Thanks, @mirceaulinic.
I think I was able to implement it as per your requests.
Sorry, but I have no confidence because I'm not an expert python/junos-eznc.
Could you please review it again?

2021-03-08 13:32 UTC, mirceaulinic approved these changes
Hey @minefuto - thanks for making the changes. It is slightly different from what I had in mind, but I like this implementation too. :smile:

2021-03-08 13:32 UTC, merged